feat: upgrade ssh2-sftp-update dependency
In quick-lint-js' builds, artifact uploads often fail [1]:

    note: Found 1 files to upload
    note: Uploading to remote directory: ***/builds/d32117cb896385a05fdc68c727535f5b9f3f9a33/manual/
    error: Error: _mkdir: Failure ***/builds/d32117cb896385a05fdc68c727535f5b9f3f9a33
        at fmtError (/Users/github-builder/github-actions-runner/_layout/_work/_actions/quick-lint/sftp-upload/master/node_modules/ssh2-sftp-client/src/utils.js:53:18)
        at /Users/github-builder/github-actions-runner/_layout/_work/_actions/quick-lint/sftp-upload/master/node_modules/ssh2-sftp-client/src/index.js:729:20
        at SFTPStream._transform (/Users/github-builder/github-actions-runner/_layout/_work/_actions/quick-lint/sftp-upload/master/node_modules/ssh2-streams/lib/sftp.js:417:17)
        at SFTPStream.Transform._write (node:internal/streams/transform:184:23)
        at writeOrBuffer (node:internal/streams/writable:389:12)
        at _write (node:internal/streams/writable:330:10)
        at SFTPStream.Writable.write (node:internal/streams/writable:334:10)
        at Channel.ondata (node:internal/streams/readable:754:22)
        at Channel.emit (node:events:394:28)
        at addChunk (node:internal/streams/readable:315:12)

This issue may have been fixed in ssh2-sftp-client upstream [2]. Upgrade
to get the potential fix.

The ssh2 package, used by ssh2-sftp-client, added an optional Node.js
native dependency. Make sure to not install it by running
'yarn install --ignore-optional' instead of just 'yarn install'.

[1] https://github.com/quick-lint/quick-lint-js/issues/491
[2] https://github.com/theophilusx/ssh2-sftp-client/issues/360

Co-Authored-By: Rishat Sultanov <sultanov-rishat@inbox.ru>